version: 1.0
component: deployment
shell: bash
timeoutInSeconds: 600

files:
  - source: artifact:/nodejs-janus-app.tar.gz
    destination: /home/ubuntu/deploy_workspace

steps:
  - stepType: Command
    name: Extract and Run Deploy Script
    runAs: root
    timeoutInSeconds: 300
    command: |
      set -euxo pipefail
      cd /home/ubuntu/deploy_workspace
      tar -xzf nodejs-janus-app.tar.gz
      chmod +x deploy.sh
      ./deploy.sh
