version: 1.0
component: deployment
shell: bash
timeoutInSeconds: 600

files:
  - source: artifact:/nodejs-janus-app.tar.gz
    destination: /home/ubuntu/deploy_workspace

steps:
  - stepType: Command
    name: Extract and Run Deploy Script
    runAs: ubuntu
    timeoutInSeconds: 300
    command: |
      set -euxo pipefail
      mkdir -p /home/ubuntu/deploy_workspace
      cd /home/ubuntu/deploy_workspace
      tar -xzf nodejs-janus-app.tar.gz
      if [ -f deploy.sh ]; then
        chmod +x deploy.sh
        ./deploy.sh
      else
        echo "❌ deploy.sh not found!"
        exit 1
      fi
