schemaVersion: "1.0"
steps:
  - type: Command
    name: Extract tar.gz
    timeoutInSeconds: 60
    command: |
      mkdir -p /home/ubuntu/deploy_workspace
      tar -xzf ${OCI_PRIMARY_ARTIFACT_FILE} -C /home/ubuntu/deploy_workspace --strip-components=0

  - type: Command
    name: Execute deploy.sh
    timeoutInSeconds: 180
    command: |
      chmod +x /home/ubuntu/deploy_workspace/deploy.sh
      /home/ubuntu/deploy_workspace/deploy.sh
